/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PaiementsRouteImport } from './routes/paiements'
import { Route as LogementsIndexRouteImport } from './routes/logements.index'
import { Route as LogementsIdRouteImport } from './routes/logements.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementsRoute = PaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => rootRouteImport,
} as any)
const LogementsIndexRoute = LogementsIndexRouteImport.update({
  id: '/logements/',
  path: '/logements/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogementsIdRoute = LogementsIdRouteImport.update({
  id: '/logements/$id',
  path: '/logements/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/paiements': typeof PaiementsRoute
  '/logements/$id': typeof LogementsIdRoute
  '/logements/': typeof LogementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/paiements': typeof PaiementsRoute
  '/logements/$id': typeof LogementsIdRoute
  '/logements': typeof LogementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/paiements': typeof PaiementsRoute
  '/logements/$id': typeof LogementsIdRoute
  '/logements/': typeof LogementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/dashboard'
    | '/login'
    | '/paiements'
    | '/logements/$id'
    | '/logements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/dashboard'
    | '/login'
    | '/paiements'
    | '/logements/$id'
    | '/logements'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/dashboard'
    | '/login'
    | '/paiements'
    | '/logements/$id'
    | '/logements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRoute: typeof ClientsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PaiementsRoute: typeof PaiementsRoute
  LogementsIdRoute: typeof LogementsIdRoute
  LogementsIndexRoute: typeof LogementsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiements': {
      id: '/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof PaiementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logements/': {
      id: '/logements/'
      path: '/logements'
      fullPath: '/logements/'
      preLoaderRoute: typeof LogementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logements/$id': {
      id: '/logements/$id'
      path: '/logements/$id'
      fullPath: '/logements/$id'
      preLoaderRoute: typeof LogementsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRoute: ClientsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PaiementsRoute: PaiementsRoute,
  LogementsIdRoute: LogementsIdRoute,
  LogementsIndexRoute: LogementsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
